services:
  sunbird-proxy:
    image: oasis256/sunbird-proxy:latest
    build:
      context: https://github.com/Oasis256/sunbird-page-translator.git#main:proxy
    ports:
      - "8787:8787"
    env_file:
      - ./.env
    restart: unless-stopped
